# Generated by Django 2.2.2 on 2019-06-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_auto_20190622_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=20)),
                ('land_address', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=20)),
                ('crop_grown', models.CharField(max_length=20)),
                ('moisture_requirement', models.IntegerField(default=0)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.Data')),
            ],
        ),
        migrations.DeleteModel(
            name='Lands',
        ),
    ]
