# Generated by Django 2.2.2 on 2019-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_link',
            field=models.URLField(default='No URLs/Websites'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_link_heading',
            field=models.CharField(default='No Heading', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger_email',
            field=models.EmailField(default='Not Available', max_length=254),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_data',
            field=models.TextField(default='No Text'),
        ),
    ]
