# Generated by Django 2.2.2 on 2019-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0006_auto_20190624_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogger_description',
            field=models.TextField(default='No Description Available'),
        ),
    ]
