# Generated by Django 2.2.2 on 2019-06-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0009_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='status',
            new_name='accepted',
        ),
    ]
