# Generated by Django 2.2.2 on 2019-06-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0011_auto_20190626_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='accepted',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
