# Generated by Django 2.2.2 on 2019-06-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0014_auto_20190626_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='accepted',
            new_name='request_status',
        ),
        migrations.AddField(
            model_name='land',
            name='district',
            field=models.CharField(default='Kanpur', max_length=20),
        ),
        migrations.AddField(
            model_name='land',
            name='expected_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='land',
            name='expected_yield',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='land',
            name='request_status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Pending', 'Pending')], default='False', max_length=7),
        ),
        migrations.AlterField(
            model_name='land',
            name='moisture_requirement',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
