# Generated by Django 2.2.2 on 2019-06-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0016_land_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='system_id',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
