# Generated by Django 2.2.2 on 2019-06-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0017_request_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='district',
            field=models.CharField(default='Kanpur', max_length=20),
            preserve_default=False,
        ),
    ]
