# Generated by Django 2.2.2 on 2019-06-26 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0018_request_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Served_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=20)),
                ('land_address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=20)),
                ('system_id', models.CharField(default='None', max_length=10)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.Data')),
            ],
        ),
    ]
