# Generated by Django 2.2.2 on 2019-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0019_served_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='expected_yield',
            field=models.FloatField(default=0.0),
        ),
    ]
