# Generated by Django 2.2.2 on 2019-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0020_auto_20190626_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='moisture',
            new_name='moisture_requirement',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='threshold',
            new_name='threshold_moisture',
        ),
        migrations.AddField(
            model_name='land',
            name='threshold_moisture',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
