# Generated by Django 2.2.2 on 2019-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0022_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
