# Generated by Django 2.2.2 on 2019-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0023_auto_20190628_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='average_moisture',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='land',
            name='last_update',
            field=models.DateTimeField(default='2019-06-19 10:47:00.000000'),
        ),
        migrations.AddField(
            model_name='land',
            name='system_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
