# Generated by Django 2.2.2 on 2019-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0024_auto_20190709_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='last_update',
            field=models.DateTimeField(default='2019-06-17 10:47:00.000000'),
        ),
    ]
